// Hw # 20: Random Number and Statistics (Lecture 47-49)
/******************************************************************************
•	Allow the user to enter the size of the dice.
•	The number of dice to roll in a single throw.
•	The number of throws to make.
•	Save the results of the dice rolls to a file (to allow for verification of the program).  
•	The file should have an opening header line that indicates size (number of sides) of the
//  dice rolled.  
•	You can decide if you want to include the number of times the dice were rolled.  
•	Then calculate the mean roll, the median roll, the standard deviation for the total number 
//  of rolls made (if you wish you can store this in the files as well as showing them on the screen).
*******************************************************************************/
//Including all necessary Header files
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>
#include "myFuncs.h"

#define f_O "diceThrowResult.txt" //This output file will have the dice throw results & average
#define f_O2 "results.txt" //This output file will have the output required for this assignment

int main()
{
    srand(time(0)); //creating seed for the rand(0) function
    
    //Displaying something on the screen
    printf("///////////////////////////////////////////////////////////////////////////\n");
    printf("                 Random Number and Statistical Analysis\n");
    printf("                    Programmed by Jonathan Hanbali\n");
    printf("///////////////////////////////////////////////////////////////////////////\n\n");
    
    //declaring integer diceSize to hold the user entered value of the size of the dice
    int diceSize;
    //prompting user to enter the size of the dice
    printf("Please enter the size of the dice:\n");
    //Scan user input and store it inside of the diceSize variable
    scanf("%i",&diceSize);
    
    //declaring integer amtOfDice to hold the user entered value of the amount of dice being thrown
    //per throw
    int amtOfDice;
    //prmopting the user to enter the amount of dice thrown
    printf("Please enter the number of dice to roll in a single throw:\n");
    //scan for the userinput
    scanf("%i",&amtOfDice);
    
    //cevlaring integer variable to hold the number of throw the user want
    int numOfThrow;
    //prompting the user to enter the number of throw desired
    printf("Please enter the number of throw you wish to make:\n");
    //scan for the user input and store it in numOfThrow variable
    scanf("%i",&numOfThrow);
    
    //creating two pointer to a file fO, and fO2
    FILE * fO;
    FILE * fO2;
    
    //both fO and fO2 will do write, and fO will hold the value of each throw, while
    //the fO2 will hold the value / prompt asked for this assignment
    fO = fopen(f_O,"w");
    fO2 = fopen(f_O2,"w");
    
    //printing the user entered value
    fprintf(fO,"The dice have %d sides\n",diceSize);
    fprintf(fO,"You want to roll %d dices\n",amtOfDice);
    fprintf(fO,"You want to throw it %d times\n\n",numOfThrow);
    
    fprintf(fO2,"The dice have %d sides\n",diceSize);
    fprintf(fO2,"You want to roll %d dices\n",amtOfDice);
    fprintf(fO2,"You want to throw it %d times\n\n",numOfThrow);
    
    //Creating a diceroll integer dynamic array with the size of numOfThrow
    int **diceRoll = (int**)malloc(numOfThrow * sizeof(int *));
    
    //using this for loop, i'm creating another dynamic array inside of the 
    //diceRoll array to hold the result of every throw 
    for(int i = 0; i < numOfThrow; i++ ) {
            diceRoll[i] = (int*)malloc(amtOfDice * sizeof( int ) );
    }
    
    //using this for loop to populate the array with the randomly generated number
    for(int i = 0; i < numOfThrow; i++){
        for(int j = 0; j < amtOfDice; j++){
            //diceRoll at i and j will be populated with a number generated by roll function
            diceRoll[i][j] = roll(diceSize);
        }
    }
    
    //creating averageDice float dynamic array with the size of numOfThrow
    //to find the average of the result of each throw
    float * averageDice = malloc(numOfThrow * sizeof(float));

    //for loop to calculate the sum of the dice 
    for(int i = 0; i < numOfThrow; i++){
        for(int j = 0; j < amtOfDice; j++){
            averageDice[i] += diceRoll[i][j];
        }
        //after summing the total of each throw, we're calculating the average by
        //dividing the total with the amount of dice
        averageDice[i] = averageDice[i] / amtOfDice;
    }

    /***************************************************************************
    * This section will output the calculated result to diceThrowResult.txt and
    * results.txt
    ***************************************************************************/
    fprintf(fO2,"Non - Sorted Average\n");
    //This for loop will print out the integer for each row and column
    for(int a = 0; a < numOfThrow; a++){
        for(int b = 0; b < amtOfDice; b++){
            if(diceSize > 0 && diceSize < 100){
                if(diceRoll[a][b] >= 10){
                    fprintf(fO,"%i ",diceRoll[a][b]);
                }else if(diceRoll[a][b] < 10){
                    fprintf(fO," %i ",diceRoll[a][b]);
                }
            }else if(diceSize >= 100){
                if(diceRoll[a][b] >= 100){
                    fprintf(fO,"%i ",diceRoll[a][b]);
                }else if(diceRoll[a][b] < 100 && diceRoll[a][b] >= 10){
                    fprintf(fO," %i ",diceRoll[a][b]);
                }else if(diceRoll[a][b] < 10){
                    fprintf(fO,"  %i ",diceRoll[a][b]);
                }
            }
        }
        fprintf(fO,"%5.2f\n",averageDice[a]);
        fprintf(fO2," %3.2f |",averageDice[a]);
    }
    
    //creating a float dynamic array to hold the value of the sortedAnswer (since the array will
    //be sorted using quick sort, so I decided to create a new array and just copu the value)
    float * sortedAnswer = malloc(numOfThrow * sizeof(float));
    //This for loop will copy the value from averageDice at b, to the sortedAnswer at b
    for(int b = 0; b < numOfThrow; b++){
        sortedAnswer[b] = averageDice[b];
    }
    
    //creating integer variable first, and last
    int first = 0, last = numOfThrow-1;
    //calling quicksort function to sort the array
    quicksort(sortedAnswer,first,last);
    
    //printing to file
    fprintf(fO2,"\nSorted Result:\n");
    //printing the sorted array
    for(int c = 0; c < numOfThrow; c++){
        fprintf(fO2, " %3.2f |",sortedAnswer[c]);
    }
    
    //print the mean value, median, variance, min, mac, and standard deviation
    fprintf(fO2,"\n\nThe average roll is: %2.2f\n",mean(sortedAnswer,numOfThrow));
    fprintf(fO2,"The median roll is: %2.2f\n",median(sortedAnswer,numOfThrow));
    fprintf(fO2,"The Variance of the roll is: %2.2f\n", variance(sortedAnswer,numOfThrow));
    fprintf(fO2,"The Standard deviation is: %2.2f\n", std_dev(sortedAnswer,numOfThrow));
    fprintf(fO2,"The max average of one roll is: %2.2f\n", max(sortedAnswer,numOfThrow));
    fprintf(fO2,"The min average of one roll is: %2.2f\n", min(sortedAnswer,numOfThrow));
    
    //freing all the memory allocated for the dynamic std::array<T, N> ;
    for(int a = 0; a < numOfThrow; a++){
        free(diceRoll[a]);
    }
    free(diceRoll);
    free(averageDice);
    free(sortedAnswer);
    return 0;
}
